--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 13-01-2017 00:49:01
-- Server version: 13.00.1722
-- Client version: 
--



USE Accounts
GO

IF DB_NAME() <> N'Accounts' SET NOEXEC ON
GO

--
-- Create table "dbo.UserTypes"
--
PRINT (N'Create table "dbo.UserTypes"')
GO
CREATE TABLE dbo.UserTypes (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  IsActive bit NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.SupplierTypes"
--
PRINT (N'Create table "dbo.SupplierTypes"')
GO
CREATE TABLE dbo.SupplierTypes (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.Suppliers"
--
PRINT (N'Create table "dbo.Suppliers"')
GO
CREATE TABLE dbo.Suppliers (
  id int IDENTITY,
  FirstName nvarchar(4000) NOT NULL,
  MiddleName nvarchar(4000) NOT NULL,
  LastName nvarchar(4000) NOT NULL,
  Age int NULL,
  MobileNo int NOT NULL,
  HomePhoneNo int NULL,
  ResidentialAddress nvarchar(4000) NOT NULL,
  BusinessAddress nvarchar(max) NULL,
  BusinessType nvarchar(max) NULL,
  ReferredByName nvarchar(max) NULL,
  RefereedByMobileNo int NOT NULL,
  CreationDate datetime NOT NULL,
  ModifiedDate datetime NOT NULL,
  Description nvarchar(4000) NULL,
  CONSTRAINT [PK_dbo.Suppliers] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.ReceivedFrom"
--
PRINT (N'Create table "dbo.ReceivedFrom"')
GO
CREATE TABLE dbo.ReceivedFrom (
  id int IDENTITY,
  Name nvarchar(500) NOT NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.ProductTypes"
--
PRINT (N'Create table "dbo.ProductTypes"')
GO
CREATE TABLE dbo.ProductTypes (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  CONSTRAINT [PK_dbo.ProductTypes] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.StockIns"
--
PRINT (N'Create table "dbo.StockIns"')
GO
CREATE TABLE dbo.StockIns (
  id int IDENTITY,
  SupplierId int NOT NULL,
  ProductTypeId int NOT NULL,
  ItemCount int NOT NULL,
  CreationDate datetime NOT NULL,
  ModifiedDate datetime NOT NULL,
  TotalSalesAmount int NULL,
  AmountPaid bit NULL,
  LoadName nvarchar(4000) NOT NULL,
  IsStocArrived bit NULL,
  SupplierTypeId int NULL,
  CONSTRAINT [PK_dbo.StockIns] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index "IX_ProductTypeId" on table "dbo.StockIns"
--
PRINT (N'Create index "IX_ProductTypeId" on table "dbo.StockIns"')
GO
CREATE INDEX IX_ProductTypeId
  ON dbo.StockIns (ProductTypeId)
  ON [PRIMARY]
GO

--
-- Create index "IX_SupplierId" on table "dbo.StockIns"
--
PRINT (N'Create index "IX_SupplierId" on table "dbo.StockIns"')
GO
CREATE INDEX IX_SupplierId
  ON dbo.StockIns (SupplierId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockIns"
--
PRINT (N'Create foreign key "[FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockIns"')
GO
ALTER TABLE dbo.StockIns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId] FOREIGN KEY (ProductTypeId) REFERENCES dbo.ProductTypes (id)
GO

--
-- Disable foreign key "[FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockIns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockIns"')
GO
ALTER TABLE dbo.StockIns
  NOCHECK CONSTRAINT [FK_dbo.StockIns_dbo.ProductTypes_ProductTypeId]
GO

--
-- Create foreign key "[FK_dbo.StockIns_dbo.Suppliers_SupplierId]" on table "dbo.StockIns"
--
PRINT (N'Create foreign key "[FK_dbo.StockIns_dbo.Suppliers_SupplierId]" on table "dbo.StockIns"')
GO
ALTER TABLE dbo.StockIns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockIns_dbo.Suppliers_SupplierId] FOREIGN KEY (SupplierId) REFERENCES dbo.Suppliers (id)
GO

--
-- Disable foreign key "[FK_dbo.StockIns_dbo.Suppliers_SupplierId]" on table "dbo.StockIns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockIns_dbo.Suppliers_SupplierId]" on table "dbo.StockIns"')
GO
ALTER TABLE dbo.StockIns
  NOCHECK CONSTRAINT [FK_dbo.StockIns_dbo.Suppliers_SupplierId]
GO

--
-- Create table "dbo.StockInReturns"
--
PRINT (N'Create table "dbo.StockInReturns"')
GO
CREATE TABLE dbo.StockInReturns (
  id int IDENTITY,
  SupplierId int NOT NULL,
  ProductTypeId int NOT NULL,
  ItemCount int NOT NULL,
  CreationDate datetime NOT NULL,
  ModifiedDate datetime NOT NULL,
  TotalSalesAmount int NULL,
  AmountPaid bit NULL,
  LoadName nvarchar(4000) NOT NULL,
  CONSTRAINT [PK_dbo.StockInReturns] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index "IX_ProductTypeId" on table "dbo.StockInReturns"
--
PRINT (N'Create index "IX_ProductTypeId" on table "dbo.StockInReturns"')
GO
CREATE INDEX IX_ProductTypeId
  ON dbo.StockInReturns (ProductTypeId)
  ON [PRIMARY]
GO

--
-- Create index "IX_SupplierId" on table "dbo.StockInReturns"
--
PRINT (N'Create index "IX_SupplierId" on table "dbo.StockInReturns"')
GO
CREATE INDEX IX_SupplierId
  ON dbo.StockInReturns (SupplierId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockInReturns"
--
PRINT (N'Create foreign key "[FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockInReturns"')
GO
ALTER TABLE dbo.StockInReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId] FOREIGN KEY (ProductTypeId) REFERENCES dbo.ProductTypes (id)
GO

--
-- Disable foreign key "[FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockInReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId]" on table "dbo.StockInReturns"')
GO
ALTER TABLE dbo.StockInReturns
  NOCHECK CONSTRAINT [FK_dbo.StockInReturns_dbo.ProductTypes_ProductTypeId]
GO

--
-- Create foreign key "[FK_dbo.StockInReturns_dbo.Suppliers_SupplierId]" on table "dbo.StockInReturns"
--
PRINT (N'Create foreign key "[FK_dbo.StockInReturns_dbo.Suppliers_SupplierId]" on table "dbo.StockInReturns"')
GO
ALTER TABLE dbo.StockInReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockInReturns_dbo.Suppliers_SupplierId] FOREIGN KEY (SupplierId) REFERENCES dbo.Suppliers (id)
GO

--
-- Disable foreign key "[FK_dbo.StockInReturns_dbo.Suppliers_SupplierId]" on table "dbo.StockInReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockInReturns_dbo.Suppliers_SupplierId]" on table "dbo.StockInReturns"')
GO
ALTER TABLE dbo.StockInReturns
  NOCHECK CONSTRAINT [FK_dbo.StockInReturns_dbo.Suppliers_SupplierId]
GO

--
-- Create table "dbo.ProductCategories"
--
PRINT (N'Create table "dbo.ProductCategories"')
GO
CREATE TABLE dbo.ProductCategories (
  id int IDENTITY,
  ProductTypeId int NOT NULL,
  Name nvarchar(max) NULL,
  CONSTRAINT [PK_dbo.ProductCategories] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index "IX_ProductTypeId" on table "dbo.ProductCategories"
--
PRINT (N'Create index "IX_ProductTypeId" on table "dbo.ProductCategories"')
GO
CREATE INDEX IX_ProductTypeId
  ON dbo.ProductCategories (ProductTypeId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId]" on table "dbo.ProductCategories"
--
PRINT (N'Create foreign key "[FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId]" on table "dbo.ProductCategories"')
GO
ALTER TABLE dbo.ProductCategories WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId] FOREIGN KEY (ProductTypeId) REFERENCES dbo.ProductTypes (id)
GO

--
-- Disable foreign key "[FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId]" on table "dbo.ProductCategories"
--
PRINT (N'Disable foreign key "[FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId]" on table "dbo.ProductCategories"')
GO
ALTER TABLE dbo.ProductCategories
  NOCHECK CONSTRAINT [FK_dbo.ProductCategories_dbo.ProductTypes_ProductTypeId]
GO

--
-- Create table "dbo.ProductSubCategories"
--
PRINT (N'Create table "dbo.ProductSubCategories"')
GO
CREATE TABLE dbo.ProductSubCategories (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  ProductCategoryId int NOT NULL,
  CONSTRAINT [PK_dbo.ProductSubCategories] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index "IX_ProductCategoryId" on table "dbo.ProductSubCategories"
--
PRINT (N'Create index "IX_ProductCategoryId" on table "dbo.ProductSubCategories"')
GO
CREATE INDEX IX_ProductCategoryId
  ON dbo.ProductSubCategories (ProductCategoryId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId]" on table "dbo.ProductSubCategories"
--
PRINT (N'Create foreign key "[FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId]" on table "dbo.ProductSubCategories"')
GO
ALTER TABLE dbo.ProductSubCategories WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId] FOREIGN KEY (ProductCategoryId) REFERENCES dbo.ProductCategories (id)
GO

--
-- Disable foreign key "[FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId]" on table "dbo.ProductSubCategories"
--
PRINT (N'Disable foreign key "[FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId]" on table "dbo.ProductSubCategories"')
GO
ALTER TABLE dbo.ProductSubCategories
  NOCHECK CONSTRAINT [FK_dbo.ProductSubCategories_dbo.ProductCategories_ProductCategoryId]
GO

--
-- Create table "dbo.ExpensesTypes"
--
PRINT (N'Create table "dbo.ExpensesTypes"')
GO
CREATE TABLE dbo.ExpensesTypes (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.Expenses"
--
PRINT (N'Create table "dbo.Expenses"')
GO
CREATE TABLE dbo.Expenses (
  id int IDENTITY,
  StockInId int NOT NULL,
  Amount int NOT NULL,
  Comments nvarchar(max) NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  ExpensesTypeId int NULL,
  CONSTRAINT [PK_dbo.Expenses] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.Expenses"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.Expenses"')
GO
CREATE INDEX IX_StockInId
  ON dbo.Expenses (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.Expenses_dbo.StockIns_StockInId]" on table "dbo.Expenses"
--
PRINT (N'Create foreign key "[FK_dbo.Expenses_dbo.StockIns_StockInId]" on table "dbo.Expenses"')
GO
ALTER TABLE dbo.Expenses WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.Expenses_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.Expenses_dbo.StockIns_StockInId]" on table "dbo.Expenses"
--
PRINT (N'Disable foreign key "[FK_dbo.Expenses_dbo.StockIns_StockInId]" on table "dbo.Expenses"')
GO
ALTER TABLE dbo.Expenses
  NOCHECK CONSTRAINT [FK_dbo.Expenses_dbo.StockIns_StockInId]
GO

--
-- Create foreign key "FK_Expenses_ExpensesTypes" on table "dbo.Expenses"
--
PRINT (N'Create foreign key "FK_Expenses_ExpensesTypes" on table "dbo.Expenses"')
GO
ALTER TABLE dbo.Expenses WITH NOCHECK
  ADD CONSTRAINT FK_Expenses_ExpensesTypes FOREIGN KEY (ExpensesTypeId) REFERENCES dbo.ExpensesTypes (id)
GO

--
-- Disable foreign key "FK_Expenses_ExpensesTypes" on table "dbo.Expenses"
--
PRINT (N'Disable foreign key "FK_Expenses_ExpensesTypes" on table "dbo.Expenses"')
GO
ALTER TABLE dbo.Expenses
  NOCHECK CONSTRAINT FK_Expenses_ExpensesTypes
GO

--
-- Create table "dbo.ExpensesesTypes"
--
PRINT (N'Create table "dbo.ExpensesesTypes"')
GO
CREATE TABLE dbo.ExpensesesTypes (
  id int IDENTITY,
  Name nvarchar(max) NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.Expenseses"
--
PRINT (N'Create table "dbo.Expenseses"')
GO
CREATE TABLE dbo.Expenseses (
  id int IDENTITY,
  StockInId int NOT NULL,
  Amount int NOT NULL,
  Comments nvarchar(max) NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  ExpensesesTypeId int NULL,
  CONSTRAINT [PK_dbo.Expenseses] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.Expenseses"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.Expenseses"')
GO
CREATE INDEX IX_StockInId
  ON dbo.Expenseses (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.Expenseses_dbo.StockIns_StockInId]" on table "dbo.Expenseses"
--
PRINT (N'Create foreign key "[FK_dbo.Expenseses_dbo.StockIns_StockInId]" on table "dbo.Expenseses"')
GO
ALTER TABLE dbo.Expenseses WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.Expenseses_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.Expenseses_dbo.StockIns_StockInId]" on table "dbo.Expenseses"
--
PRINT (N'Disable foreign key "[FK_dbo.Expenseses_dbo.StockIns_StockInId]" on table "dbo.Expenseses"')
GO
ALTER TABLE dbo.Expenseses
  NOCHECK CONSTRAINT [FK_dbo.Expenseses_dbo.StockIns_StockInId]
GO

--
-- Create foreign key "FK_Expenseses_ExpensesesTypes" on table "dbo.Expenseses"
--
PRINT (N'Create foreign key "FK_Expenseses_ExpensesesTypes" on table "dbo.Expenseses"')
GO
ALTER TABLE dbo.Expenseses WITH NOCHECK
  ADD CONSTRAINT FK_Expenseses_ExpensesesTypes FOREIGN KEY (ExpensesesTypeId) REFERENCES dbo.ExpensesesTypes (id)
GO

--
-- Disable foreign key "FK_Expenseses_ExpensesesTypes" on table "dbo.Expenseses"
--
PRINT (N'Disable foreign key "FK_Expenseses_ExpensesesTypes" on table "dbo.Expenseses"')
GO
ALTER TABLE dbo.Expenseses
  NOCHECK CONSTRAINT FK_Expenseses_ExpensesesTypes
GO

--
-- Create table "dbo.SupplierPayment"
--
PRINT (N'Create table "dbo.SupplierPayment"')
GO
CREATE TABLE dbo.SupplierPayment (
  id int IDENTITY,
  StockInId int NULL,
  ExpensesesId int NULL,
  Amount decimal NULL,
  CreationDate datetime NULL DEFAULT (getdate()),
  ModifiedDate datetime NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create foreign key "FK_SupplierPayment_Expenseses" on table "dbo.SupplierPayment"
--
PRINT (N'Create foreign key "FK_SupplierPayment_Expenseses" on table "dbo.SupplierPayment"')
GO
ALTER TABLE dbo.SupplierPayment WITH NOCHECK
  ADD CONSTRAINT FK_SupplierPayment_Expenseses FOREIGN KEY (ExpensesesId) REFERENCES dbo.Expenseses (id)
GO

--
-- Disable foreign key "FK_SupplierPayment_Expenseses" on table "dbo.SupplierPayment"
--
PRINT (N'Disable foreign key "FK_SupplierPayment_Expenseses" on table "dbo.SupplierPayment"')
GO
ALTER TABLE dbo.SupplierPayment
  NOCHECK CONSTRAINT FK_SupplierPayment_Expenseses
GO

--
-- Create foreign key "FK_SupplierPayment_StockIns" on table "dbo.SupplierPayment"
--
PRINT (N'Create foreign key "FK_SupplierPayment_StockIns" on table "dbo.SupplierPayment"')
GO
ALTER TABLE dbo.SupplierPayment WITH NOCHECK
  ADD CONSTRAINT FK_SupplierPayment_StockIns FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "FK_SupplierPayment_StockIns" on table "dbo.SupplierPayment"
--
PRINT (N'Disable foreign key "FK_SupplierPayment_StockIns" on table "dbo.SupplierPayment"')
GO
ALTER TABLE dbo.SupplierPayment
  NOCHECK CONSTRAINT FK_SupplierPayment_StockIns
GO

--
-- Create table "dbo.Customers"
--
PRINT (N'Create table "dbo.Customers"')
GO
CREATE TABLE dbo.Customers (
  id int IDENTITY,
  FirstName nvarchar(4000) NOT NULL,
  MiddleName nvarchar(4000) NOT NULL,
  LastName nvarchar(4000) NOT NULL,
  Age int NULL,
  MobileNo int NOT NULL,
  HomePhoneNo int NULL,
  ResidentialAddress nvarchar(4000) NOT NULL,
  BusinessAddress nvarchar(max) NULL,
  ReferredByName nvarchar(max) NULL,
  ReferredById int NOT NULL,
  RefereedByMobileNo int NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  Description nvarchar(4000) NULL,
  CONSTRAINT [PK_dbo.Customers] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.StockOuts"
--
PRINT (N'Create table "dbo.StockOuts"')
GO
CREATE TABLE dbo.StockOuts (
  id int IDENTITY,
  StockInId int NOT NULL,
  CustomerId int NOT NULL,
  ItemCount int NOT NULL,
  ItemPrice float NOT NULL,
  Amount int NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  CONSTRAINT [PK_dbo.StockOuts] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index "IX_CustomerId" on table "dbo.StockOuts"
--
PRINT (N'Create index "IX_CustomerId" on table "dbo.StockOuts"')
GO
CREATE INDEX IX_CustomerId
  ON dbo.StockOuts (CustomerId)
  ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.StockOuts"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.StockOuts"')
GO
CREATE INDEX IX_StockInId
  ON dbo.StockOuts (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.StockOuts_dbo.Customers_CustomerId]" on table "dbo.StockOuts"
--
PRINT (N'Create foreign key "[FK_dbo.StockOuts_dbo.Customers_CustomerId]" on table "dbo.StockOuts"')
GO
ALTER TABLE dbo.StockOuts WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockOuts_dbo.Customers_CustomerId] FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (id)
GO

--
-- Disable foreign key "[FK_dbo.StockOuts_dbo.Customers_CustomerId]" on table "dbo.StockOuts"
--
PRINT (N'Disable foreign key "[FK_dbo.StockOuts_dbo.Customers_CustomerId]" on table "dbo.StockOuts"')
GO
ALTER TABLE dbo.StockOuts
  NOCHECK CONSTRAINT [FK_dbo.StockOuts_dbo.Customers_CustomerId]
GO

--
-- Create foreign key "[FK_dbo.StockOuts_dbo.StockIns_StockInId]" on table "dbo.StockOuts"
--
PRINT (N'Create foreign key "[FK_dbo.StockOuts_dbo.StockIns_StockInId]" on table "dbo.StockOuts"')
GO
ALTER TABLE dbo.StockOuts WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockOuts_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.StockOuts_dbo.StockIns_StockInId]" on table "dbo.StockOuts"
--
PRINT (N'Disable foreign key "[FK_dbo.StockOuts_dbo.StockIns_StockInId]" on table "dbo.StockOuts"')
GO
ALTER TABLE dbo.StockOuts
  NOCHECK CONSTRAINT [FK_dbo.StockOuts_dbo.StockIns_StockInId]
GO

--
-- Create table "dbo.StockOutReturns"
--
PRINT (N'Create table "dbo.StockOutReturns"')
GO
CREATE TABLE dbo.StockOutReturns (
  id int IDENTITY,
  StockInId int NOT NULL,
  CustomerId int NOT NULL,
  ItemCount int NOT NULL,
  ItemPrice float NOT NULL,
  Amount int NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  CONSTRAINT [PK_dbo.StockOutReturns] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index "IX_CustomerId" on table "dbo.StockOutReturns"
--
PRINT (N'Create index "IX_CustomerId" on table "dbo.StockOutReturns"')
GO
CREATE INDEX IX_CustomerId
  ON dbo.StockOutReturns (CustomerId)
  ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.StockOutReturns"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.StockOutReturns"')
GO
CREATE INDEX IX_StockInId
  ON dbo.StockOutReturns (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.StockOutReturns_dbo.Customers_CustomerId]" on table "dbo.StockOutReturns"
--
PRINT (N'Create foreign key "[FK_dbo.StockOutReturns_dbo.Customers_CustomerId]" on table "dbo.StockOutReturns"')
GO
ALTER TABLE dbo.StockOutReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockOutReturns_dbo.Customers_CustomerId] FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (id)
GO

--
-- Disable foreign key "[FK_dbo.StockOutReturns_dbo.Customers_CustomerId]" on table "dbo.StockOutReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockOutReturns_dbo.Customers_CustomerId]" on table "dbo.StockOutReturns"')
GO
ALTER TABLE dbo.StockOutReturns
  NOCHECK CONSTRAINT [FK_dbo.StockOutReturns_dbo.Customers_CustomerId]
GO

--
-- Create foreign key "[FK_dbo.StockOutReturns_dbo.StockIns_StockInId]" on table "dbo.StockOutReturns"
--
PRINT (N'Create foreign key "[FK_dbo.StockOutReturns_dbo.StockIns_StockInId]" on table "dbo.StockOutReturns"')
GO
ALTER TABLE dbo.StockOutReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.StockOutReturns_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.StockOutReturns_dbo.StockIns_StockInId]" on table "dbo.StockOutReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.StockOutReturns_dbo.StockIns_StockInId]" on table "dbo.StockOutReturns"')
GO
ALTER TABLE dbo.StockOutReturns
  NOCHECK CONSTRAINT [FK_dbo.StockOutReturns_dbo.StockIns_StockInId]
GO

--
-- Create table "dbo.Sales"
--
PRINT (N'Create table "dbo.Sales"')
GO
CREATE TABLE dbo.Sales (
  id int IDENTITY,
  StockInId int NOT NULL,
  CustomerId int NOT NULL,
  NoOfProduct int NOT NULL,
  Price int NOT NULL,
  Amount int NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  CONSTRAINT [PK_dbo.Sales] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index "IX_CustomerId" on table "dbo.Sales"
--
PRINT (N'Create index "IX_CustomerId" on table "dbo.Sales"')
GO
CREATE INDEX IX_CustomerId
  ON dbo.Sales (CustomerId)
  ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.Sales"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.Sales"')
GO
CREATE INDEX IX_StockInId
  ON dbo.Sales (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.Sales_dbo.Customers_CustomerId]" on table "dbo.Sales"
--
PRINT (N'Create foreign key "[FK_dbo.Sales_dbo.Customers_CustomerId]" on table "dbo.Sales"')
GO
ALTER TABLE dbo.Sales WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.Sales_dbo.Customers_CustomerId] FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (id)
GO

--
-- Disable foreign key "[FK_dbo.Sales_dbo.Customers_CustomerId]" on table "dbo.Sales"
--
PRINT (N'Disable foreign key "[FK_dbo.Sales_dbo.Customers_CustomerId]" on table "dbo.Sales"')
GO
ALTER TABLE dbo.Sales
  NOCHECK CONSTRAINT [FK_dbo.Sales_dbo.Customers_CustomerId]
GO

--
-- Create foreign key "[FK_dbo.Sales_dbo.StockIns_StockInId]" on table "dbo.Sales"
--
PRINT (N'Create foreign key "[FK_dbo.Sales_dbo.StockIns_StockInId]" on table "dbo.Sales"')
GO
ALTER TABLE dbo.Sales WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.Sales_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.Sales_dbo.StockIns_StockInId]" on table "dbo.Sales"
--
PRINT (N'Disable foreign key "[FK_dbo.Sales_dbo.StockIns_StockInId]" on table "dbo.Sales"')
GO
ALTER TABLE dbo.Sales
  NOCHECK CONSTRAINT [FK_dbo.Sales_dbo.StockIns_StockInId]
GO

--
-- Create table "dbo.SalesReturns"
--
PRINT (N'Create table "dbo.SalesReturns"')
GO
CREATE TABLE dbo.SalesReturns (
  id int IDENTITY,
  StockInId int NOT NULL,
  SalesId int NOT NULL,
  CustomerId int NOT NULL,
  NoOfItems int NOT NULL,
  Price int NOT NULL,
  Amount int NOT NULL,
  Comments nvarchar(max) NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  CONSTRAINT [PK_dbo.SalesReturns] PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index "IX_CustomerId" on table "dbo.SalesReturns"
--
PRINT (N'Create index "IX_CustomerId" on table "dbo.SalesReturns"')
GO
CREATE INDEX IX_CustomerId
  ON dbo.SalesReturns (CustomerId)
  ON [PRIMARY]
GO

--
-- Create index "IX_SalesId" on table "dbo.SalesReturns"
--
PRINT (N'Create index "IX_SalesId" on table "dbo.SalesReturns"')
GO
CREATE INDEX IX_SalesId
  ON dbo.SalesReturns (SalesId)
  ON [PRIMARY]
GO

--
-- Create index "IX_StockInId" on table "dbo.SalesReturns"
--
PRINT (N'Create index "IX_StockInId" on table "dbo.SalesReturns"')
GO
CREATE INDEX IX_StockInId
  ON dbo.SalesReturns (StockInId)
  ON [PRIMARY]
GO

--
-- Create foreign key "[FK_dbo.SalesReturns_dbo.Customers_CustomerId]" on table "dbo.SalesReturns"
--
PRINT (N'Create foreign key "[FK_dbo.SalesReturns_dbo.Customers_CustomerId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.SalesReturns_dbo.Customers_CustomerId] FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (id)
GO

--
-- Disable foreign key "[FK_dbo.SalesReturns_dbo.Customers_CustomerId]" on table "dbo.SalesReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.SalesReturns_dbo.Customers_CustomerId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns
  NOCHECK CONSTRAINT [FK_dbo.SalesReturns_dbo.Customers_CustomerId]
GO

--
-- Create foreign key "[FK_dbo.SalesReturns_dbo.Sales_SalesId]" on table "dbo.SalesReturns"
--
PRINT (N'Create foreign key "[FK_dbo.SalesReturns_dbo.Sales_SalesId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.SalesReturns_dbo.Sales_SalesId] FOREIGN KEY (SalesId) REFERENCES dbo.Sales (id)
GO

--
-- Disable foreign key "[FK_dbo.SalesReturns_dbo.Sales_SalesId]" on table "dbo.SalesReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.SalesReturns_dbo.Sales_SalesId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns
  NOCHECK CONSTRAINT [FK_dbo.SalesReturns_dbo.Sales_SalesId]
GO

--
-- Create foreign key "[FK_dbo.SalesReturns_dbo.StockIns_StockInId]" on table "dbo.SalesReturns"
--
PRINT (N'Create foreign key "[FK_dbo.SalesReturns_dbo.StockIns_StockInId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns WITH NOCHECK
  ADD CONSTRAINT [FK_dbo.SalesReturns_dbo.StockIns_StockInId] FOREIGN KEY (StockInId) REFERENCES dbo.StockIns (id)
GO

--
-- Disable foreign key "[FK_dbo.SalesReturns_dbo.StockIns_StockInId]" on table "dbo.SalesReturns"
--
PRINT (N'Disable foreign key "[FK_dbo.SalesReturns_dbo.StockIns_StockInId]" on table "dbo.SalesReturns"')
GO
ALTER TABLE dbo.SalesReturns
  NOCHECK CONSTRAINT [FK_dbo.SalesReturns_dbo.StockIns_StockInId]
GO

--
-- Create table "dbo.PaymentReceived"
--
PRINT (N'Create table "dbo.PaymentReceived"')
GO
CREATE TABLE dbo.PaymentReceived (
  id int IDENTITY,
  CustomerId int NOT NULL,
  Amount int NOT NULL,
  CreationDate datetime NOT NULL DEFAULT (getdate()),
  ModifiedDate datetime NOT NULL DEFAULT (getdate()),
  Comments nvarchar(max) NULL,
  ReceivedFromTypeId int NOT NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key "FK_PaymentReceived_Customers" on table "dbo.PaymentReceived"
--
PRINT (N'Create foreign key "FK_PaymentReceived_Customers" on table "dbo.PaymentReceived"')
GO
ALTER TABLE dbo.PaymentReceived WITH NOCHECK
  ADD CONSTRAINT FK_PaymentReceived_Customers FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (id)
GO

--
-- Disable foreign key "FK_PaymentReceived_Customers" on table "dbo.PaymentReceived"
--
PRINT (N'Disable foreign key "FK_PaymentReceived_Customers" on table "dbo.PaymentReceived"')
GO
ALTER TABLE dbo.PaymentReceived
  NOCHECK CONSTRAINT FK_PaymentReceived_Customers
GO

--
-- Create foreign key "FK_PaymentReceived_ReceivedFrom" on table "dbo.PaymentReceived"
--
PRINT (N'Create foreign key "FK_PaymentReceived_ReceivedFrom" on table "dbo.PaymentReceived"')
GO
ALTER TABLE dbo.PaymentReceived WITH NOCHECK
  ADD CONSTRAINT FK_PaymentReceived_ReceivedFrom FOREIGN KEY (ReceivedFromTypeId) REFERENCES dbo.ReceivedFrom (id)
GO

--
-- Disable foreign key "FK_PaymentReceived_ReceivedFrom" on table "dbo.PaymentReceived"
--
PRINT (N'Disable foreign key "FK_PaymentReceived_ReceivedFrom" on table "dbo.PaymentReceived"')
GO
ALTER TABLE dbo.PaymentReceived
  NOCHECK CONSTRAINT FK_PaymentReceived_ReceivedFrom
GO

--
-- Create table "dbo.AppUserTypes"
--
PRINT (N'Create table "dbo.AppUserTypes"')
GO
CREATE TABLE dbo.AppUserTypes (
  AppUserTypeId int IDENTITY,
  AppUserType nvarchar(max) NULL,
  CONSTRAINT PK_AppUserTypes PRIMARY KEY CLUSTERED (AppUserTypeId)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table "dbo.AppUsers"
--
PRINT (N'Create table "dbo.AppUsers"')
GO
CREATE TABLE dbo.AppUsers (
  AppUserId int IDENTITY,
  FirstName nvarchar(4000) NOT NULL,
  MiddleName nvarchar(4000) NOT NULL,
  LastName nvarchar(4000) NOT NULL,
  Age int NULL,
  AppUserTypeId int NOT NULL,
  MobileNo int NOT NULL,
  HomePhoneNo int NULL,
  ResidentialAddress nvarchar(4000) NOT NULL,
  BusinessAddress nvarchar(max) NULL,
  ReferredByName nvarchar(max) NULL,
  ReferredById int NOT NULL,
  RefereedByMobileNo int NOT NULL,
  CreationDate datetime NULL,
  ModifiedDate datetime NULL,
  Description nvarchar(4000) NULL,
  CONSTRAINT [PK_dbo.AppUsers] PRIMARY KEY CLUSTERED (AppUserId)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key "FK_AppUsers_AppUsers" on table "dbo.AppUsers"
--
PRINT (N'Create foreign key "FK_AppUsers_AppUsers" on table "dbo.AppUsers"')
GO
ALTER TABLE dbo.AppUsers WITH NOCHECK
  ADD CONSTRAINT FK_AppUsers_AppUsers FOREIGN KEY (AppUserTypeId) REFERENCES dbo.AppUserTypes (AppUserTypeId)
GO

--
-- Disable foreign key "FK_AppUsers_AppUsers" on table "dbo.AppUsers"
--
PRINT (N'Disable foreign key "FK_AppUsers_AppUsers" on table "dbo.AppUsers"')
GO
ALTER TABLE dbo.AppUsers
  NOCHECK CONSTRAINT FK_AppUsers_AppUsers
GO

--
-- Create table "dbo.Profit"
--
PRINT (N'Create table "dbo.Profit"')
GO
CREATE TABLE dbo.Profit (
  id int IDENTITY,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO
SET NOEXEC OFF
GO